### ISSUE TITLE
how to set fft length

### ISSUE THREAD

**Issue by yaxiongchi** [ah42/cuda-p1#1]
A few exponents with known factors, with min b1 and b2 necessary to find them, and a reasonable fft length to use:
50001781  94,709	4,067,587  2688k
51558151	 5,953	2,034,041  2880k
54447193	 1,181	  682,009  3072k
58610467	70,843	  694,201  3200k
61012769	10,273	1,572,097  3360k

different exponents, how to set different FFT lengths？

**Comment by BleuSquid** [comment]
If you want to specify a specific FFT length for a given exponent, that can be done through the -f argument on the command line. E.g. for you first example:
` ./CUDAPm1.exe -f 2688k -b1 94709 -b2 4067587 50001781`

However, while it might be the most reasonable FFT length, it is almost certainly not the fastest FFT length. Often, a slightly larger FFT will perform much more efficiently. On my 4070ti, for example, 2744k is the most efficient FFT length for this exponent. The optimal FFT length for a given exponent will vary depending on hardware and CUDA versions.

Usually the best thing to do is run the CUFFT Benchmark before-hand, which generates a list of optimal FFT lengths for the program to select from, and then let the program choose from that list when you give it an exponent.

To cover the FFT range for your examples, you could run the benchmark over FFTs from 2048k through 4096k (pure powers of 2 are the fastest, so I tend to use them as my starting and ending points) with -cufftbench 2048 4096 r (where r is the number of iterations to test. A higher number will take longer, but will produce a more accurate average time).

This takes about 30 seconds for me: `./CUDAPm1.exe -cufftbench 2048 4096 10` and produces an output file `NVIDIAGeForceRTX4070Ti_fft.txt` with these as the most efficient FFT lengths. The next time I give the program an exponent, it will use this file to select the appropriate FFT size.
```
Device              NVIDIA GeForce RTX 4070 Ti
Compatibility       8.9
clockRate (MHz)     2760
memClockRate (MHz)  10501

  fft    max exp  ms/iter
 2304   43194913   0.9626
 2592   48471289   1.1923
 2744   51250889   1.3492
 2880   53735041   1.4103
 3200   59570449   1.4628
 3456   64229677   1.4883
 3584   66556463   1.6568
 3600   66847171   1.8180
 3888   72075517   1.8749
 4032   74686523   1.9773
 4096   75846319   2.0876
```
